// <auto-generated />
using System;
using CourseRegistrationApp.Data.SqlRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseRegistrationApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210818201405_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("CourseRegistrationApp.Models.Courses", b =>
                {
                    b.Property<int>("C_CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("C_CourseDescrip")
                        .HasColumnType("longtext");

                    b.Property<string>("C_CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("C_CourseNumber")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsS_Id")
                        .HasColumnType("int");

                    b.HasKey("C_CourseId");

                    b.HasIndex("StudentsS_Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseRegistrationApp.Models.Student", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("C_CourseId")
                        .HasColumnType("int");

                    b.Property<string>("S_Email")
                        .HasColumnType("longtext");

                    b.Property<string>("S_FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("S_LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("S_PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("S_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseRegistrationApp.Models.Courses", b =>
                {
                    b.HasOne("CourseRegistrationApp.Models.Student", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsS_Id");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
